export const projectsData = {
  personal: [
    {
      title: "QR Code Generator",
      image: "images/qr-code-generator.png",
      tech: "Spring Boot / AWS S3",
      desc: "Backend microservice for QR generation",
      link: "https://github.com/Junior-Stranner/QR-Code-generator",
    },
    {
      title: "Notification API",
      image: "images/foto notificacao website.png",
      tech: "Spring Boot / JavaMail",
      desc: "API to notify when someone accesses my portfolio",
      link: "#",
    },
    {
      title: "Mini Fullstack API",
      image: "images/userAuth.png",
      tech: "Spring Boot / React / Docker",
      desc: "Fullstack application to manage products",
      link: "https://github.com/Junior-Stranner/Fullstack-Challenge-Docker",
    },
    {
      title: "E-commerce Microservice",
      image: "images/mic-pedidos.png",
      tech: "Spring Boot / RabbitMQ",
      desc: "Order microservice for e-commerce system",
      link: "https://github.com/Junior-Stranner/e-commerce",
    },
    {
      title: "Online Library (JPA)",
      image: "images/Add Authrntication Ju.png",
      tech: "Java / Spring Data JPA",
      desc: "Library system with relational entities",
      link: "https://github.com/Junior-Stranner/Online-Bibliotec-DataJPA",
    },
    {
      title: "Bundesliga Simulator",
      image: "images/bundesliga-simulator.png",
      tech: "JavaScript / HTML / CSS",
      desc: "Football simulation platform",
      link: "https://judev-simulator.netlify.app/",
    },
    {
      title: "Login Page",
      image: "images/Tela Cadastro Signup.png",
      tech: "Spring Security / Angular",
      desc: "Authentication system with login and signup",
      link: "https://github.com/Junior-Stranner/Fullstack-Login-Page",
    },
    {
      title: "Parking API",
      image: "images/Add Authrntication Ju.png",
      tech: "Spring Boot / JWT / Swagger",
      desc: "Parking management API",
      link: "https://github.com/Junior-Stranner/parking-api",
    },
    {
      title: "Online Library (Thymeleaf)",
      image: "images/Biblioteca-Online.jpeg",
      tech: "Spring Boot / Thymeleaf",
      desc: "First library system using Spring MVC",
      link: "https://github.com/Junior-Stranner/Online-Bibliotec",
    },
    {
      title: "Pix Payment API",
      image: "images/Email-send.png",
      tech: "Spring Boot / Security / JavaMail",
      desc: "Pix payment simulation system",
      link: "https://github.com/Junior-Stranner/Pix-Payment-System",
    },
    {
      title: "Programming Logic Exercises",
      image: "images/Java-vs-C-Sharp.jpg",
      tech: "Java / C#",
      desc: "Workbook of logic and data structure exercises",
      link: "https://github.com/Junior-Stranner/Developer-Challenge-Trainment",
    },
    {
      title: "Twitter Clone",
      image: "images/twitter-app.webp",
      tech: "Java / OAuth2",
      desc: "Simple Twitter-like application",
      link: "https://github.com/Junior-Stranner/Ageny-Haven",
    },
    {
      title: "TecEvent",
      image: "images/technology-innovation-digital-evolution-homepage.avif",
      tech: "Spring Boot / AWS / Docker",
      desc: "Tech event simulation system",
      link: "https://github.com/Junior-Stranner/EventoTec-spring",
    },
    {
      title: "CRUD in PHP",
      image: "",
      tech: "PHP / HTML / CSS",
      desc: "First CRUD project",
      link: "#",
    },
  ],

  collaborations: [
    {
      title: "LocateCar System",
      image: "images/Projeto-final-ada-LocateCar.png",
      tech: "Java OOP",
      desc: "Car rental system built with a team",
      link: "https://github.com/Kimidarious/projeto2-ada-meli-locateCar",
    },
    {
      title: "ADA Challenges M2",
      image: "images/desafio-ada-m2.png",
      tech: "Java OOP",
      desc: "Challenges solved via fork contributions",
      link: "https://github.com/Junior-Stranner/oopII",
    },
    {
      title: "ADA Challenges M1",
      image: "images/desafio-ada-m1.png",
      tech: "Java OOP",
      desc: "Programming challenges to prove skills",
      link: "https://github.com/Junior-Stranner/Desafios-ADA-ML",
    },
    {
      title: "Haven Agency Website",
      image: "images/mobile-Tik-Tok-pages.png",
      tech: "HTML / CSS / JavaScript",
      desc: "Freelance website for a streaming agency",
      link: "https://github.com/Junior-Stranner/Ageny-Haven",
    },
  ],

  academic: [
    {
      title: "Online Library (Bootcamp Final)",
      image: "",
      tech: "Java OOP",
      desc: "Final project built with a teammate",
      link: "https://github.com/HJ-Technologies-ADA-ML/Biblioteca-Virtual",
    },
  ],
};
