export const skillsData = [
  { name: "Java", icon: "bx bxl-java" },
  { name: "Spring Framework", icon: "bx bxl-spring-boot" },
  { name: "Spring Boot", icon: "bx bxl-spring-boot" },
  { name: "Spring Data JPA", icon: "bx bx-data" },
  { name: "JPA & Hibernate", icon: "bx bx-data" },
  { name: "JDBC", icon: "bx bx-data" },
  { name: "JSP", icon: "bx bxl-java" },
  { name: "Thymeleaf", icon: "bx bxl-spring-boot" },
  { name: "PostgreSQL", icon: "bx bx-data" },
  { name: "MySQL", icon: "bx bx-data" },
  { name: "Swagger OpenAPI", icon: "bx bxl-swagger" },
  { name: "Spring Security", icon: "bx bx-shield-quarter" },
  { name: "JWT", icon: "bx bx-key" },
  { name: "C#", icon: "bx bx-code-curly" },
  { name: "JavaScript", icon: "bx bxl-javascript" },
  { name: "Postman", icon: "bx bx-paper-plane" },
  { name: "Docker", icon: "bx bxl-docker" },
  { name: "Microservices", icon: "bx bx-server" },
];
